blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
  url(r'^$', views.IndexView.as_view(), name='index'),
  url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
  url(r'^(?P<post_id>\d+)/comment/', views.comment, name='comment'),
)

inspiratect_test/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length=255)
  slug = models.SlugField(unique=True, max_length=255)
  description = models.CharField(max_length=255)
  content = models.TextField()
  published = models.BooleanField(default=True)
  created_at = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ['-created_at']

  def __unicode__(self):
    return self.title

class Comment(models.Model):
  post = models.ForeignKey(Post)
  name = models.CharField(max_length=255)
  text = models.TextField()
  created_at = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ['-created_at']

  def __unicode__(self):
    return self.name

blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from blog.models import Post, Comment

# Create your views here.
class IndexView(generic.ListView):
  template_name = 'blog/index.html'
  model = Post

class DetailView(generic.DetailView):
  model = Post
  template_name = 'blog/detail.html'

def comment(request, post_id):
  post = get_object_or_404(Post, pk=post_id)
  post.comment_set.create(name=request.POST['name'], text=request.POST['text'])
  return HttpResponseRedirect(reverse('detail', args=(post.id,)))

blog/templates/base.html
{% load staticfiles %}

<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />

<html>
  <head>
    <title>Jabs Blog</title>
  </head>
  <body>
    <div class="blog">
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="/">Jabs Blog</a>
          </div>
        </div>
      </div>

      <div class="container">
        {% block content %}{% endblock %}
      </div>
    </div>
  </body>
</html>

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block content %}

  <div class="panel">
    <div class="page-header">
      <h1>{{post.title}}</h1>
    </div>
    <p class="">
      {{post.content}}
    </p>
  </div>

  <div class="comments panel panel-default">
    <h4 class="panel-heading">Comentários:</h4>
    <table class='table table-striped'>
      <tr class='name'>
        <th>
          <strong>Nome</strong>
        </th>
        <th>
          <strong>Comentário</strong>
        </th>
      </tr>
      {% for comment in post.comment_set.all %}
      <tr>
        <td>
          <strong>{{comment.name}}</strong>
        </td>
        <td>
          {{comment.text}}
        </td>
      </tr>
      {% endfor %}
    </table>
  </div>



  <h4>Adicione um comentário:</h4>
  <form action="{% url 'comment' post.id %}" method="post" role="form">
    {% csrf_token %}
    <div class="form-group">
      <label for="name">Nome:</label>
      <input type="text" name="name" class="form-control">
    </div>

    <div class="form-group">
      <label for="name">Comentário:</label>
      <textarea name="text" cols="40" rows="10" class="form-control"></textarea>
    </div>
    <input class="btn btn-default" type="submit" value="Postar Comentário" />
  </form>

{% endblock %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block content %}
  {% if post_list %}
      <div class="post">
      {% for post in post_list %}
          <a href="{% url 'detail' post.id %}"><h3>{{post.title}}</h3></a>
          <div class="text">{{post.content}}</div>
      {% endfor %}
      </div>
  {% else %}
      <div>Não existem Posts no blog ):</div>
  {% endif %}
{% endblock %}